backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "/public/img"
publish_mode: editorial_workflow
public_folder: "/img"
local_backend: true 
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/_posts"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown"}
